/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#23005c",
        "secondary-fixed": "#e9ddff",
        "inverse-primary": "#494bd6",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#301400",
        "primary-fixed": "#e1e0ff",
        "inverse-surface": "#e5e1e4",
        "on-secondary-container": "#c4abff",
        "tertiary-fixed": "#ffdcc5",
        background: "#131315",
        "tertiary-container": "#d97721",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#e5e1e4",
        "surface-tint": "#c0c1ff",
        "surface-container-high": "#2a2a2c",
        "secondary-container": "#571bc1",
        "outline-variant": "#464554",
        "tertiary-fixed-dim": "#ffb783",
        tertiary: "#ffb783",
        outline: "#908fa0",
        "secondary-fixed-dim": "#d0bcff",
        "primary-container": "#8083ff",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1d",
        "on-tertiary": "#4f2500",
        "on-background": "#e5e1e4",
        "on-primary": "#1000a9",
        "on-tertiary-container": "#452000",
        "primary-fixed-dim": "#c0c1ff",
        error: "#ffb4ab",
        "on-primary-container": "#0d0096",
        "error-container": "#93000a",
        "surface-container-highest": "#353437",
        "on-primary-fixed": "#07006c",
        primary: "#c0c1ff",
        "surface-variant": "#353437",
        "surface-bright": "#39393b",
        "inverse-on-surface": "#313032",
        "on-tertiary-fixed-variant": "#703700",
        "surface-dim": "#131315",
        surface: "#131315",
        "surface-container": "#201f22",
        "on-surface-variant": "#c7c4d7",
        "on-secondary": "#3c0091",
        secondary: "#d0bcff",
        "surface-container-lowest": "#0e0e10",
        "on-secondary-fixed-variant": "#5516be"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-margin": "24px",
        gutter: "16px",
        "header-height": "56px",
        unit: "4px",
        "sidebar-width": "240px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        h2: ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h3: ["Geist", "sans-serif"],
        h1: ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        mono: ["13px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
